
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEQ = 36;
  public static final int CONS = 29;
  public static final int LBRACKET = 6;
  public static final int MULT = 22;
  public static final int ASSIGNMENT = 30;
  public static final int POOL = 43;
  public static final int XOR = 24;
  public static final int LPAREN = 10;
  public static final int SEMI = 13;
  public static final int BADCHAR = 48;
  public static final int MINUS = 21;
  public static final int RPAREN = 11;
  public static final int GRE = 18;
  public static final int NOT = 25;
  public static final int AND = 26;
  public static final int IN = 28;
  public static final int OR = 27;
  public static final int TDEF = 32;
  public static final int COMMA = 12;
  public static final int FI = 38;
  public static final int DIV = 23;
  public static final int LOOP = 42;
  public static final int PLUS = 20;
  public static final int IF = 37;
  public static final int MAIN = 2;
  public static final int ID = 47;
  public static final int DOT = 14;
  public static final int LE = 17;
  public static final int EOF = 0;
  public static final int RETURN = 46;
  public static final int RBRACKET = 7;
  public static final int error = 1;
  public static final int BREAK = 41;
  public static final int FDEF = 33;
  public static final int EQ = 16;
  public static final int TOP = 34;
  public static final int PDT = 35;
  public static final int COLON = 5;
  public static final int LITERAL = 4;
  public static final int ELSE = 40;
  public static final int LBRACE = 8;
  public static final int READ = 44;
  public static final int THEN = 39;
  public static final int RBRACE = 9;
  public static final int LEQ = 19;
  public static final int ALIAS = 31;
  public static final int LABEL = 3;
  public static final int PRINT = 45;
  public static final int NOTEQ = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAIN",
  "LABEL",
  "LITERAL",
  "COLON",
  "LBRACKET",
  "RBRACKET",
  "LBRACE",
  "RBRACE",
  "LPAREN",
  "RPAREN",
  "COMMA",
  "SEMI",
  "DOT",
  "NOTEQ",
  "EQ",
  "LE",
  "GRE",
  "LEQ",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "XOR",
  "NOT",
  "AND",
  "OR",
  "IN",
  "CONS",
  "ASSIGNMENT",
  "ALIAS",
  "TDEF",
  "FDEF",
  "TOP",
  "PDT",
  "SEQ",
  "IF",
  "FI",
  "THEN",
  "ELSE",
  "BREAK",
  "LOOP",
  "POOL",
  "READ",
  "PRINT",
  "RETURN",
  "ID",
  "BADCHAR"
  };
}

